sendwithus/sendwithus_php

lib/API.php, test/APITest.php
Support for GET /customers/matt@sendwithus.com + Test
(sorry for duplicate request)
=> implement get_customer method

lib/API.php
End point for requesting all logs specific to a single customer
=> Added get all customer logs

README.md, lib/API.php, test/APITest.php
Added UTC args to logs. Added an extra test + README changes.
=> Added ability to get logs before/after timestamp

lib/API.php
Make it possible to more easily implement custom adjustments by
extending this class.
=> Make vendor more easily extensible

lib/API.php, test/APITest.php
Hi,
We needed to use you batch api from our client in php and realised that it wasn't implemented there. I could find that it is implemented in your python client so I did a shameless port from the python client to the php client :)
I'm filling this pull request since maybe you find it useful to add it to your php client (and we would love that since then we won't need to extend your code in our codebase but just update from composer instead and thats it :) )
Please let me know your thoughts and if there is some cleaning/fixing that needs to be done before be able to merge it!
Cheers
=> Ports BathAPI from Python client

README.md
added sample calls and response objects
=> added conversion api

lib/API.php
In this version:
- Better batch execution and cancellation.
=> Update version number

README.md, lib/API.php, test/APITest.php
Added possibility to provide already base64 encoded files to the API.
=> Provide encoded files

lib/API.php
Sending inlined files is now more flexible. The file name and content
now be specified directly.
=> Increment version to push new changes

README.md, lib/API.php, test/APITest.php
Add ability to resend mails based on given log_id.
=> Implement resend API

.travis.yml
Test on travis in current php versions as well
=> Test on current php versions

.github/PULL_REQUEST_TEMPLATE, README.md
This PR adds a pull request template and fixes minor typos in the README. The PR template will help contributors produce higher quality pull requests that can be accepted more quickly.
=> Add PR template and update README

README.md
Removes Gmail Link from the README.
Adding a Gmail account is not supported. 
N/A
=> Remove Gmail Link

test/APITest.php
- Fixes test testCreateEmailSuccess
=> Fix failing tests for email version and customers

README.md, lib/API.php, test/APITest.php
Deprecating the Log List API endpoint.
- Update README to reflect Log List API changes
- Remove Log List API support from library
The endpoint has been deprecated and will later be removed. We are updating the client to reflect this.
Unit tests have been removed that rely on Log List API code.
=> Deprecate the Log List API

README.md, lib/API.php, test/APITest.php
Updating the API class to allow for an extra option containing a custom log handler.
Resolves #74 
I've added a two unit tests that go through the 2 flows:
- one using the default logging method (using error_log) 
- a second one that uses the custom log handler
- New feature (non-breaking change which adds functionality)
=> [Issue #74] Added custom log handler

.travis.yml, README.md, lib/API.php
This is simply a maintenance PR that updates:
- the README
- client version number
- TravisCI configuration to get PHP 5.3 working again
=> Update version & clean up

.github/CODEOWNERS, test/APITest.php
This PR:
- updates the CODEOWNERS file to notify the Sendwithus review team. 
- fixes an integration test that would occasionally fail due to a race condition.
=> Update Codeowners and test

test/APITest.php
This PR addresses an integration test that would occasionally fail due to a race condition.
=> Update delete customer test

lib/API.php
Increment the version to v6.3.0 to reflect the latest changes.
=> Increment version
